<?= $this->doctype() ?>

<html lang="it">
	<head>
		<meta charset="utf-8">
		<?= $this->headTitle('Pomodoro timer')->setSeparator(' - ')->setAutoEscape(false) ?>

		<?= $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<!-- Styles -->
		<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
			->prependStylesheet($this->basePath('css/style.css'))
			->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
			->prependStylesheet($this->basePath('css/bootstrap.min.css'))
		?>

		<!-- Scripts -->
		<?php
			$now = new DateTime();
			$version = $now->getTimestamp();
		?>
		<?= 
			$this->headScript()
				->prependFile($this->basePath('js/auth.class.js?'.$version))
				->prependFile($this->basePath('js/bootstrap.min.js'))
				->prependFile($this->basePath('js/jquery-3.1.0.min.js'))

		?>
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="<?= $this->url('home') ?>">
						<img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" />
					</a>
					<span class="navbar-brand">&nbsp;Pomodoro timer (sostituire con le info dell'utente loggato)</span>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav navbar-right" id="identityMenu">
						<li><p class="navbar-text"></p></li>
						<li><a href="#" class="logout hide">Logout</a></li>
					</ul>
				</div>
			</div>
		</nav>

		<div class="container">
			<?= $this->content ?>
			<hr>
		</div>
		<?= $this->inlineScript() ?>
	</body>
</html>
