<div class="jumbotron" style="text-align: center;">
	<h1>PomoTimer</h1>
		<div id="signin">
			<?php if(!is_null($this->token) && $this->token !== "") {?>
				<script>
					sessionStorage.setItem("access_token", "<?= $this->token ?>");
					$("a.logout").removeClass("hide");
				</script>
				SONO LOGGATO: token-> <?php echo $this->token; ?>
			<?php }?>
			<script>
				if(sessionStorage.getItem("access_token") === null || sessionStorage.getItem("access_token") === "") {
					$("a.logout").addClass("hide");
					$("#signin").append("<h3>Not logged in</h3>");
					$("#signin").append("<p><a href='#' id='githubLogin'>Github Log In</a></p>");
				}
			</script>
		</div>


</div>
